### PR TITLE
Add BUILD_EDITOR option to control cdogs-sdl-editor build

### PR DESCRIPTION
**Pull request by vilhelmgray**

### CODE REVIEW

**Comment by vilhelmgray** [comment]
Is the search for OpenGL package only needed for `cdogs-sdl-editor`?
https://github.com/cxong/cdogs-sdl/blob/146039ee2f6f1c6690ecd01a901b93c2349c7b22/CMakeLists.txt#L68
If so, I can add a conditional check for that so we don't need to needlessly search for it if we're not building the editor.

**Comment by cxong** [comment]
yes; opengl is only used for nuklear GUI used in the editor

**Comment by vilhelmgray** [comment]
All right, I went ahead and added the conditional check before searching for the OpenGL package. :+1:

**Comment by cxong** [comment]
Thanks :+1:

**Pull request merged**
