### PR TITLE
Automatic multiOS deployment

### LINKED ISSUE #348: Automatic Windows deployment
Similar to #290, see if we can configure Appveyor to build the Windows package and deploy as part of the release process.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9340750-travis-ci-windows-deployment?utm_campaign=plugin&utm_content=tracker%2F347422&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F347422&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by neverscaired**
It resolves #348 
Don't forget to change token to yours.
Test release:
https://github.com/neverscaired/cdogs-sdl/releases/tag/WindowsDeployment

### CODE REVIEW

**Comment by neverscaired** [comment]
I am testing gcw-0 deploy right now and will write here about results.

**Comment by neverscaired** [comment]
Sorry, misclicked button

**Comment by neverscaired** [comment]
Deploy completes !!!
Now it deploys win32,rpm,deb, tar.gz (linux),GCW-Zero
see test release: https://github.com/neverscaired/cdogs-sdl/releases/tag/gcw_test
I am using CPack for deployment (via make package),so there shouldn't be regressions or something wrong in builds.
You can pull it.

**Comment by cxong** [comment]
Great, a few points:

- rpm/deb aren't required; I'm not 100% sure but I think these depend on the exact distro anyway
- The linux tar.gz and windows exe files are much smaller than usual, compare to the last release for example: https://github.com/cxong/cdogs-sdl/releases/tag/0.6.2-2. I think you're missing all the data files, the tar.gz only has the bin directory for example. Note that the windows release should include all the DLLs required to run the game. These need to be copied from the SDL folders.
- If you're looking at the OSX deployment, there's a similar issue. Currently I'm building manually via Xcode, and the libraries are DMGs that are dropped into `/Library/Frameworks`. I'm not sure how homebrew works but you might need to do something similar - the game should run without the user needing to install SDL, run `brew install` commands etc.

**Comment by neverscaired** [comment]
Mising files in packages is a very strange behaviour if you used "make package" command for deployment same as me, . I'll see deeper. Problem with osx SDL2 dependences is already solved, I'll pull that commits latter when it will be ready completely.

**Comment by neverscaired** [comment]
Now it resolves #376 too.
I implemented osx deployment too, however all builds contain just bin folder (I guess)
test release: https://github.com/neverscaired/cdogs-sdl/releases/tag/osx3
Could you tell me exact steps when you deploy app?
I am using "make && make package", but most of data is missing.

**Comment by neverscaired** [comment]
Good news.
I fixed packages for linux & osx.
Plz test GCW-0 package (it seems to be ok, but I am not sure)
Things to do: add dll-s to win32 package

**Comment by cxong** [comment]
The osx package doesn't work; it's looking for libraries in `/usr/local/opt`. Usually this is where homebrew installs libraries. I'm not familiar with homebrew but I think its libraries are different to the .dmg ones that are downloaded from libsdl.org. The homebrew libraries will need to be bundled into the package somehow.

**Comment by neverscaired** [comment]
I removed homebrew version of SDL2 and it fails compile now. However I tried to compile your last release and it fails too. I tried to launch app from your last release's dmg, and it failes to run.
So the questions are:
Are you SURE that your compile code is correct?
Are you SURE that your dmg release runs correctly on OSX?

Please tell me your osx version and how SDL2 is installed (via homebrew, via dmg,both)

**Comment by cxong** [comment]
I tested the last releases and looks like they won't run as-is - they will close immediately with no output.

The problem is that the files are under file quarantine, which is something OS X automatically does on untrusted downloaded files. I guess I missed this problem because I only test the package before uploading, and not after downloading them. To work around this, after installing to `/Applications`, run

    xattr -rc /Applications/cdogs-sdl

And everything should work. The last release, 0.6.2 works after doing this.

Obviously this is very inconvenient for end users, they already have to do the control-click open thing to get around the unidentified developer thing. I'll look into this problem but for your work, just use the `xattr` workaround and don't worry about this.

My OS X version is el capitan / sierra. SDL is downloaded from libsdl.org, from the .dmg files. You can find build/package instructions at https://github.com/cxong/cdogs-sdl/wiki/Developer-Getting-Started:-OSX-Xcode and https://github.com/cxong/cdogs-sdl/wiki/Packaging:-OSX - note that it's built using Xcode.

As for automatic packaging, Xcode can be invoked on the command line so perhaps travis CI can build it that way. The existing CMakeLists.txt should build the .dmg, including copying the SDL libraries from `/Library/Frameworks`. Otherwise if you use homebrew, you'll have to include the libraries (I think they're the `.dylib` files) inside the package. Something like this, although I haven't tried: http://stackoverflow.com/q/19209515/2038264

**Comment by neverscaired** [comment]
Windows package is fine now (I've tested it). I wrote bat-script to get sdl2 dlls.
See https://github.com/neverscaired/cdogs-sdl/releases/tag/WinTest

Now I will focus on OSX. Do you think that deploying *.dylib files into package is acceptable solution?

**Comment by neverscaired** [comment]
Ohhhhh
Finally I've got it working. The problem was in using 7z for work with dmg archives. This problem damaged symbolic links on extracting. Using "hdiutil" for osx sdl2 installing fixes issue. It's ready to merge (I've tested osx,win32,linux builds) See https://github.com/neverscaired/cdogs-sdl/releases/tag/final
Please check .opk file and don't forget to change tokens int .travis.yml and appveyor.yml files

**Comment by cxong** [comment]
The windows package seems to be missing dlls.

**Comment by neverscaired** [comment]
You packed dlls files from src dir but I moved them to "dll" dir.
After install:
C:\Program Files (x86)\C-Dogs SDL\bin>dir
 Volume in drive C has no label.
 Volume Serial Number is 2414-8FD0

 Directory of C:\Program Files (x86)\C-Dogs SDL\bin

11/08/2016  04:50 PM    <DIR>          .
11/08/2016  04:50 PM    <DIR>          ..
11/08/2016  03:42 PM           938,060 cdogs-sdl-editor.exe
11/08/2016  03:42 PM           919,704 cdogs-sdl.exe
11/05/2016  03:16 AM           367,104 libFLAC-8.dll
11/05/2016  03:17 AM           223,232 libjpeg-9.dll
11/05/2016  03:16 AM           401,920 libmodplug-1.dll
11/05/2016  03:16 AM            47,104 libogg-0.dll
11/05/2016  03:17 AM           200,704 libpng16-16.dll
11/05/2016  03:17 AM           436,224 libtiff-5.dll
11/05/2016  03:16 AM           196,096 libvorbis-0.dll
11/05/2016  03:16 AM            62,976 libvorbisfile-3.dll
11/05/2016  03:17 AM           271,872 libwebp-4.dll
11/05/2016  03:15 AM         1,068,544 SDL2.dll
11/05/2016  03:17 AM            93,184 SDL2_image.dll
11/05/2016  03:16 AM           186,368 SDL2_mixer.dll
11/05/2016  03:16 AM           301,568 smpeg2.dll
11/05/2016  03:17 AM           123,904 zlib1.dll
              16 File(s)      5,838,564 bytes
               2 Dir(s)  104,845,623,296 bytes free

**Comment by neverscaired** [comment]
I am sorry, my bad. Fixed.
See https://github.com/neverscaired/cdogs-sdl/releases/tag/final2

**Comment by neverscaired** [comment]
Are you intrested in win64 build ?

**Comment by cxong** [comment]
No; we'll need 32 bit build anyway for better compatibility; I don't know if there are any advantages for having a 64 bit build at this point.

**Comment by neverscaired** [comment]
So is this pull request ready?I fixed missing dlls, all builds are fine (.opk doesn't testede but looks fine)

**Comment by cxong** [comment]
I'll make some time to test the release. macOS looks ok, although I noticed that the SDL frameworks that should have symlinks are instead hard links which is inflating the dmg size - I think you can use a flag for `cp`: http://superuser.com/q/138587/197238

**Comment by neverscaired** [comment]
Nice idea about osx, I used it. .dmg file size decreased from 34mb to 14mb.
See https://github.com/neverscaired/cdogs-sdl/releases/tag/final3

**Comment by cxong** [comment]
Looks great! Can I put you in the credits for this work, and under which name?

**Comment by cxong** [comment]
when creating the tokens, which scopes are needed?

**Comment by neverscaired** [comment]
You can use "Vadim Barkov" name.
About scopes:
 - [ ] repo  Full control of private repositories
      - [ ] repo:status  Access commit status
      - [ ] repo_deployment  Access deployment status
      - [x] public_repo  Access public repositories

This is about travis ci. I enabled repo_deployment for Appveyor but think this is not needed.
You can use your old tokens. Just fix them before merge.

**Pull request merged**
