### PR TITLE
Possible fix to 489 "Blood splatter speed should be based on mass"

### PR DESCRIPTION
**Pull request by davidrgmcb**
Not totally sure I have this fixed if only because increasing mass for testing tends to send enemies flying across the map but I at least think this will work.

### CODE REVIEW

**Comment by cxong** [comment]
no this is incomplete; you've added a Mass parameter to ActorHit but nothing is populating it yet. Find the place where the ActorHit event is being created (GAME_EVENT_ACTOR_HIT) and populate the mass field.

Also, the Hostname field renaming is unnecessary.

**Comment by davidrgmcb** [comment]
Apologies on Hostname renaming, the version of HostName in the msg.options file was labelled as HostName and that conflicted with several instances in msg.proto so I changed the one that created the fewest conflicts, my apologies, I should have requested clarification or at least made note of why I'd done it. 

Thanks for the response, will attempt to fix.

**Comment by davidrgmcb** [comment]
If additional changes need to be made let me know,  not sure if I've messed up an obvious point on this

**Comment by cxong** [comment]
Thanks; could you please fix up the conflicts?

**Comment by cxong** [comment]
👍

**Pull request merged**
