### PR TITLE
Fix wildcard use in names for Travis Releases

### PR DESCRIPTION
**Pull request by meZee**
Add `file_glob: true` in .travis.yml

### CODE REVIEW

**Comment by cxong** [comment]
Success! https://github.com/cxong/cdogs-sdl/releases/tag/travis_deploy_test3 :tada: 

well, almost; please let me test the attached binaries first.

**Comment by meZee** [comment]
congusbongus__,  the.deb seems to fail on ubuntu, spewing something about invalid character  "\` \'". When I extract it via `dpkg-deb --extact`, and attempt to run it, it complains about not finding `GLIBC_2.14`. 

    root@debian:/home/mezee/Desktop# dpkg -i C-Dogs.SDL-0.5.7-Linux.deb
    dpkg: error processing C-Dogs.SDL-0.5.7-Linux.deb (--install): 
    parsing file '/var/lib/dpkg/tmp.ci/control' near line 1:
    invalid package name (character \` ' not allowed (only letters, digits and characters \`-+._'))
    Errors were encountered while processing: C-Dogs.SDL-0.5.7-Linux.deb

The .rpm also fails to install on Fedora compaining about missing depends(`sdl_image >= 1.2` & `sdl_mixer >= 1.2`) despite the depends(`SDL_image = 1.2.12-11` & `SDL_mixer = 1.2.12-7`) being satisfied, I believe it may be related to naming conventions in the Fedora repo's with linux being case-sensitive(notice case difference in above packages).

I'm not familiar with SuSe, and I'm going to test on Ubuntu, which should work, perhaps with the same invalid package name issue.

**Comment by carstene1ns** [comment]
As said, bingcc might help with glibc version pinning, and yes, it seems like I messed up the package names (again... doh! :no_good:)
Thanks for testing and sorry for the inconvenience.

**Comment by meZee** [comment]
As I suspected both Ubuntu(14.04), and Linux Mint 17 could run the binary after extraction, but the installers failed with the same invalid package name issue. Also, I had incorrectly escaped the above error, but that should be resolved now.

**Pull request merged**
