### PR TITLE
Fix division by zero in vec2i_inverse

### PR DESCRIPTION
**Pull request by veikkos**
Fix division by zero in vec2i_inverse. Noticed by MSVC15.

### CODE REVIEW

**Comment by cxong** [comment]
Interesting! Although the upstream is https://github.com/felselva/mathc, and I see they removed vec2i_inverse, and C-Dogs SDL doesn't use vec2i_inverse, so I guess we should update mathc.h and mathc.c. Good find!

**Comment by veikkos** [comment]
> Interesting! Although the upstream is https://github.com/felselva/mathc, and I see they removed vec2i_inverse, and C-Dogs SDL doesn't use vec2i_inverse, so I guess we should update mathc.h and mathc.c. Good find!

Alright. I only fixed it because it blocks MSVC15 release build due to a warning which is considered as an error. I was guessing it's not used because it was completely unusable. :)

**Comment by cxong** [comment]
Looks like there is an API break - `svec2_is_nearly_equal` has been removed. Hopefully the author can add it in: felselva/mathc#39

**Comment by veikkos** [comment]
> 
> 
> Looks like there is an API break - `svec2_is_nearly_equal` has been removed. Hopefully the author can add it in: [felselva/mathc#39](https://github.com/felselva/mathc/issues/39)

Alright, good. Should we create a separate issue for the update? And maybe consider merging this in the meanwhile since it blocks the MSVC release build? Not sure why it doesn't block debug build.

**Pull request merged**
